config/routes.rb
Rails.application.routes.draw do
	mount ActionCable.server => '/cable'

	root 'static_pages#home'
	get '/home', to: 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/company', to: 'static_pages#company'
	get '/privacy', to: 'static_pages#privacy'
	get '/dashboard', to: 'static_pages#dashboard'
	get '/search_unship_order', to: 'static_pages#search_unship_order'
	get '/shipments', to:'static_pages#shipments'
	get '/introducing', to: 'static_pages#introducing'
	get '/signup', to: 'users#new'
	post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users, :except => [:new,:create]
	resources :account_activations, only: [:edit]
	resources :stocks, path: 'shipments/stocks'
	post '/shipments/stocks/complete', to: 'stocks#complete'
	resources :postages, path: 'shipments/postages'
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :items
	resources :users, shallow: true do
		resources :rooms, shallow: true do
			resources :messages
		end
	end


	namespace :admin do
		resources :postages, :stocks
		resources :users, shallow: true do
			resources :order_products, :rooms
		end
		get 'order_products/update_shipment_week/:farmer_id', to: 'order_products#update_shipment_week'
	end
	get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/ec_data/order_product.rb
module EcData
  class OrderProduct < EcData::Base
    belongs_to :stock, class_name:"Stock"
    belongs_to :order_list, class_name:"EcData::OrderList"
    belongs_to :product, class_name:"EcData::Product"
    has_one :room
    
    enum priority: { normal: 0, high: 1, top: 2 }
    
    def shipment_danger
      return (priority == "top") || (order_list.payment.paid && order_list.payment.paid_at.since(10.day).past? && trailing_id.nil?) || (order_list.payment.paid && order_list.buyer_address.desired_delivery && order_list.buyer_address.desired_delivery_date.ago(2.day).past?)
    end
    
    def shipment_caution
      return (priority == "high") || (order_list.payment.paid && order_list.payment.paid_at.since(7.day).past? && trailing_id.nil?) || (order_list.payment.paid && order_list.buyer_address.desired_delivery && order_list.buyer_address.desired_delivery_date.ago(5.day).past?)
    end
    
    def send_shipment_complete(user)
      order_list = EcData::OrderList.find_by(id:self.order_list_id)
      buyer_address = order_list.buyer_address
      sending_address = order_list.sending_address unless buyer_address.same_sending_address
      product = EcData::Product.find_by(id:self.product_id)
      postage = user.postages.find_by(item_type:self.product_id)
      OrderMailer.shipment_notification(order:self,buyer_address:buyer_address,sending_address:sending_address ,product:product,postage:postage).deliver_now
    end
  end
end

app/controllers/admin/order_products_controller.rb
class Admin::OrderProductsController < Admin::ApplicationController
  
  def index
    @farmer = User.find(params[:user_id])
    if params[:unship_order] == "true"
      @order_products = ::EcData::OrderProduct.eager_load(:order_list, {order_list: :buyer_address}, {order_list: :sending_address}, {order_list: :payment}).where(stock_id: @farmer.stock_ids).where.not(addresses: {desired_delivery: true}).where(trailing_id: nil).where(payments:{paid: true}).order("order_products.bought_time ASC").paginate(page: params[:page], per_page: 10)
    elsif params[:desired_delivery] == "true"
      @order_products = ::EcData::OrderProduct.eager_load(:order_list, {order_list: :buyer_address}, {order_list: :sending_address}, {order_list: :payment}).where(stock_id: @farmer.stock_ids).where(addresses: {desired_delivery: true}).where(payments:{paid: true}).where(trailing_id: nil).order("addresses.desired_delivery_date ASC").paginate(page: params[:page], per_page: 10)
    else
      @order_products = ::EcData::OrderProduct.eager_load(:order_list, {order_list: :buyer_address}, {order_list: :sending_address}, {order_list: :payment}).where(stock_id: @farmer.stock_ids).order("order_products.bought_time ASC").paginate(page: params[:page], per_page: 10)
    end
  end

  def edit
    @order_product = ::EcData::OrderProduct.find(params[:id])
    @farmer = @order_product.stock.user
    @farmer_stocks = @farmer.stocks.order("salable DESC")
    @product = @order_product.product
    @product_farmers = @order_product.product.users
    @buyer_address = @order_product.order_list.buyer_address
    unless @buyer_address.same_sending_address
      @sending_address = @order_product.order_list.sending_address
    else
      @sending_address = @buyer_address
    end
  end

  def update
    @order_product = ::EcData::OrderProduct.find(params[:id])
    @farmer = @order_product.stock.user
    if @order_product.update_attributes(op_params)
      flash[:success] = "注文情報の更新が完了しました"
      redirect_to admin_user_order_products_path(@farmer)
    else
      flash.now[:danger] = "注文情報の更新に失敗しました。"
      render 'new'
    end
  end

  def destroy
  end

  def update_shipment_week
    @farmer = User.find(params[:farmer_id].to_i)
    @farmer_stocks = @farmer.stocks.where(product_id:params[:product_id].to_i).order("salable DESC")
    render :partial => 'shipment_week'
  end

  private

  def op_params
    params.require(:ec_data_order_product).permit(:stock_id,:priority)
  end
end

app/views/admin/order_products/_op.html.erb
<% if op.order_list.sending_address.present? %>
<% sending_address = op.order_list.sending_address %>
<% else %>
<% sending_address = op.order_list.buyer_address %>
<% end %>
<% if op.shipment_danger %>
<ul class="list-items--row sp-list-items--row danger">
<% elsif op.shipment_caution %>
<ul class="list-items--row sp-list-items--row caution">
<% else %>
<ul class="list-items--row sp-list-items--row">
<% end %>
  <li class="list-items--row__item sp-list-items--row__item">
    <%= op.bought_time.strftime('%Y年%m月%d日 %H:%M') %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item">
    <%= op.product.name %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item quantity">
    <%= op.quantity %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item">
    <%= sending_address.lastname %><%= sending_address.firstname %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item sending-address">
    <%= sending_address.pref %><%= sending_address.city %><%= sending_address.street %><br/><%= sending_address.building %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item quantity">
    <% if op.order_list.payment.paid %>
    <span><%= icon('far', 'circle') %></span>
    <% else %>
    <span><%= icon('fas', 'times') %></span>
    <% end %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item">
    <% if op.order_list.buyer_address.desired_delivery %>
    <%= op.order_list.buyer_address.shipment_date %><br/><%= op.order_list.buyer_address.shipment_time %>
    <% else %>
    <%= icon('fas', 'times') %>
    <% end %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item">
    <% if op.trailing_id.present? %>
    <span>発送済み</span>
    <% else %>
    <span>未発送</span>
    <% end %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item button">
    <%= link_to "編集", edit_admin_order_product_path(op) %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item button">
    <% if op.room.nil? %>
      <% room = Room.new %>
      <% user_id = params[:id] || params[:user_id] %>
      <%= form_for(room, :url => admin_user_rooms_path(user_id: user_id)) do | f | %>
        <%= f.hidden_field :order_product_id, value:op.id %>
        <button type="submit" class="form__items__item--icon-button"><%= icon('far', 'comments') %></button>
      <% end %>
    <% else %>
      <%= link_to room_path(op.room) do %>
        <%= icon('far', 'comments') %>
      <% end %>
    <% end %>
  </li>
</ul>

app/views/admin/order_products/_shipment_week.html.erb
<label for="ec_data_order_product_stock_id" class="form__select-items__item--label sp-form__select-items__item--label">登録週</label>
<%= collection_select :ec_data_order_product, :stock_id, @farmer_stocks, :id, :salable, {}, {:class => "form__select-items__item--select sp-form__select-items__item--select"} %>

app/views/admin/order_products/edit.html.erb
<div class="side">
  <%= render 'layouts/dashboard_sidebar' %>
</div>
<div class="main admin-order-product_edit">
	<div>
		<h1>注文情報の編集</h1>
		<ul class="list-items--column sp-list-items--column">
			<li class="list-items--column__item sp-list-items--column__item">
				<ul class="list-items--row sp-list-items--row">
					<li class="list-items--row__item label">購入日時</li>
					<li class="list-items--row__item data"><%= @order_product.bought_time.strftime("%Y年%m月%d日 %H:%M") %></li>
				</ul>
				<% if @buyer_address.desired_delivery %>
				<ul class="list-items--row sp-list-items--row">
					<li class="list-items--row__item label">配送指定日時</li>
					<li class="list-items--row__item data"><%= @buyer_address.shipment_date %>　<%= @buyer_address.shipment_time %></li>
				</ul>
				<% end %>
				<ul class="list-items--row sp-list-items--row">
					<li class="list-items--row__item label">注文内容</li>
					<li class="list-items--row__item data"><%= @product.name %></li>
				</ul>
				<ul class="list-items--row sp-list-items--row">
					<li class="list-items--row__item label">数量</li>
					<li class="list-items--row__item data"><%= @order_product.quantity %>個</li>
				</ul>
			</li>
		</ul>
		<ul class="list-items--column sp-list-items--column">
			<li class="list-items--column__item sp-list-items--column__item">
				<ul class="list-items--row sp-list-items--row">
					<li class="list-items--row__item label">購入者氏名</li>
					<li class="list-items--row__item data"><%= @buyer_address.lastname %><%= @buyer_address.firstname %></li>
				</ul>
				<ul class="list-items--row sp-list-items--row">
					<li class="list-items--row__item label">送付先氏名</li>
					<li class="list-items--row__item data"><%= @sending_address.lastname %><%= @sending_address.firstname %></li>
				</ul>
				<ul class="list-items--row sp-list-items--row">
					<li class="list-items--row__item label">送付先住所</li>
					<li class="list-items--row__item data"><%= @sending_address.pref %><%= @sending_address.city %><%= @sending_address.street %><%= @sending_address.building %></li>
				</ul>
			</li>
		</ul>
		<%= form_for @order_product, :url => {action: "update"}, :html => {class: "form sp-form", style: "align-self:center;"} do |f| %>
			<%= f.hidden_field :product_id, value: @product.id %>
			<div class="form__select-items sp-form__select-items">
				<label for="order_product_farmer_id" class="form__select-items__item--label sp-form__select-items__item--label">生産者名</label>
				<%= collection_select :order_product, :farmer_id, @product_farmers, :id, :corporate_name, {:selected => @farmer.id} , {:class => "form__select-items__item--select sp-form__select-items__item--select"} %>
			</div>
			<div class="form__select-items sp-form__select-items shipment_week">
				<label for="ec_data_order_product_stock_id" class="form__select-items__item--label sp-form__select-items__item--label">登録週</label>
				<%= f.collection_select :stock_id, @farmer_stocks , :id, :salable, { :selected => @order_product.stock_id}, {:class => "form__select-items__item--select sp-form__select-items__item--select"} %>
			</div>
			<div class="form__select-items sp-form__select-items">
				<label for="ec_data_order_product_priority" class="form__select-items__item--label sp-form__select-items__item--label">優先順位</label>
				<%= f.select :priority, EcData::OrderProduct.priorities.map { |k,v| [t("order_product.priority.#{k}"), k]} , {} , {:class => "form__select-items__item--select sp-form__select-items__item--select"} %>
			</div>
			<div class="button-container">
				<button type="submit" class="action-button">
					<span>更新する</span>
				</button>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/order_products/index.html.erb
<div class="side">
	<%= render 'layouts/dashboard_sidebar' %>
</div>
<div class="main admin-order-product_index">
  <% if params[:desired_delivery] == "true" %>
  <h1><%= @farmer.corporate_name %>　未発送の日時指定の注文一覧</h1>
  <% elsif params[:unship_order] == "true" %>
  <h1><%= @farmer.corporate_name %>　未発送の注文一覧</h1>
  <% else %>
  <h1><%= @farmer.corporate_name %>　注文一覧</h1>
  <% end %>
  <ul class="list-items--column sp-list-items--column">
    <li class="list-items--column__item sp-list-items--column__item">
      <%= link_to "注文一覧に切り替え", admin_user_order_products_path(user_id: @farmer.id) %>
    </li>
    <li class="list-items--column__item sp-list-items--column__item">
      <%= link_to "未発送の注文一覧に切り替え", admin_user_order_products_path(user_id: @farmer.id, params: {unship_order: true}) %>
    </li>
    <li class="list-items--column__item sp-list-items--column__item">
      <%= link_to "未発送の日時指定注文一覧に切り替え", admin_user_order_products_path(user_id: @farmer.id, params: {desired_delivery: true}) %>
    </li>
  </ul>
  <ul class="list-items--column sp-list-items--column">
    <ul class="list-items--row sp-list-items--row">
      <li class="list-items--row__item sp-list-items--row__item">
      <% if params[:desired_delivery] == "true" %>
      配送指定日
      <% else %>
      購入日
      <% end %>
      </li>
      <li class="list-items--row__item sp-list-items--row__item">商品名</li>
      <li class="list-items--row__item sp-list-items--row__item quantity">数量</li>
      <li class="list-items--row__item sp-list-items--row__item">発送先氏名</li>
      <li class="list-items--row__item sp-list-items--row__item sending-address">発送先住所</li>
      <li class="list-items--row__item sp-list-items--row__item quantity">入金</li>
      <li class="list-items--row__item sp-list-items--row__item">配送指定</li>
      <li class="list-items--row__item sp-list-items--row__item">発送状況</li>
      <li class="list-items--row__item sp-list-items--row__item button"></li>
      <li class="list-items--row__item sp-list-items--row__item button"></li>
    </ul>
    <%= render :partial => "op", :collection => @order_products %>
    <%= will_paginate @order_products %>
  </ul>
</div>