config/routes.rb
Rails.application.routes.draw do
	mount ActionCable.server => '/cable'

	root 'static_pages#home'
	get '/home', to: 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/company', to: 'static_pages#company'
	get '/privacy', to: 'static_pages#privacy'
	get '/dashboard', to: 'static_pages#dashboard'
	get '/search_unship_order', to: 'static_pages#search_unship_order'
	get '/shipments', to:'static_pages#shipments'
	get '/introducing', to: 'static_pages#introducing'
	get '/signup', to: 'users#new'
	post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users, :except => [:new,:create]
	resources :account_activations, only: [:edit]
	resources :stocks, path: 'shipments/stocks'
	post '/shipments/stocks/complete', to: 'stocks#complete'
	resources :postages, path: 'shipments/postages'
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :items
	resources :users, shallow: true do
		resources :rooms, shallow: true do
			resources :messages
		end
	end


	namespace :admin do
		resources :postages, :stocks
		resources :users, shallow: true do
			resources :order_products, :rooms
		end
		get 'order_products/update_shipment_week/:farmer_id', to: 'order_products#update_shipment_week'
	end
	get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/postage.rb
class Postage < ApplicationRecord
  belongs_to :user,  optional: true
  
  validates :item_type, presence: true
  validates :company, presence: true
  validates :hokkaido, presence:true
  validates :kitatouhoku, presence: true, allow_blank:true
  validates :minamitouhoku, presence: true, allow_blank:true
  validates :touhoku, presence: true, allow_blank:true
  validates :kantou, presence: true
  validates :tokyo, presence: true , allow_blank:true
  validates :shinetsu, presence: true
  validates :hokuriku, presence: true
  validates :chubu, presence: true
  validates :kansai, presence: true
  validates :chugoku, presence: true
  validates :shikoku, presence: true
  validates :kyushu, presence: true , allow_blank:true
  validates :kitakyushu, presence: true , allow_blank:true
  validates :minamikyushu, presence: true , allow_blank:true
  validates :okinawa, presence: true , allow_blank:true
  
end

app/controllers/admin/postages_controller.rb
class Admin::PostagesController < Admin::ApplicationController
	before_action :admin_execute, only: [:update]

	def index
		@user = User.find(params[:user_id])
		@postages = user.postages.paginate(page: params[:page], per_page: 10)
	end

	def edit
		@postage = Postage.find(params[:id])
	end

	def update
		@postage = Postage.find(params[:id])
		if @postage.update_attributes(postage_params)
			redirect_to root_path
		else
			flash[:danger] = "編集に失敗しました。"
			render 'edit'
		end
	end

end

app/controllers/postages_controller.rb
class PostagesController < ApplicationController
  before_action :logged_in_user
  include PostagesHelper
  
  def index
    @postages = current_user.postages
  end
  
  def new
    @postage = Postage.new
    @postage_list = product_list
  end
  
  def create
    @postage = current_user.postages.build(postage_params)
    if @postage.save
      redirect_to dashboard_path, flash: { success: "送料の設定が完了しました。"}
    else
      render 'new'
    end
  end
  
  def edit
    @postage = Postage.find(params[:id])
    @postage_list = product_list
  end
  
  def update
    @postage = Postage.find(params[:id])
    if @postage.update_attributes(postage_params)
      redirect_to postage_path(@postage)
    else
      render 'edit'
    end
  end
  
  def show
    @postage = Postage.find(params[:id])
  end
  
  def delete
    @postage = Postage.find(params[:id])
    if @postage.destroy
      redirect_to dashboard_path
    else
      redirect_to postage_path(@postage)
    end
  end
  private
  
  def postage_params
    params.require(:postage).permit(:area,:item_type,:company,:hokkaido,:touhoku,:kitatouhoku,:minamitouhoku,:kantou,:tokyo,:hokuriku,:shinetsu,:chubu,:kansai,:chugoku,:shikoku,:kyushu,:kitakyushu,:minamikyushu,:okinawa)
  end
end

app/helpers/postages_helper.rb
module PostagesHelper
  
  def postage_list
    list = []
    factor = [["季節の野菜セット", "MiddleBox"]]
    postages = current_user.postages
    if postages.blank?
      return factor
    else
      for item in factor do
        for postage in postages do
          list.push(item) if postage.item_type != item[1]
        end
      end
      return list
    end
  end
  
end

app/views/postages/_form.html.erb
<%= form_for @postage do | f | %>
<%= f.hidden_field :area, value:current_user.area %>
<div>
  <%= f.label :item_type, "発送する商品" %>
  <% if controller.action_name == "edit" %>
    <% if @postage.item_type == "MiddleBox" %>
    <div>季節の野菜セット</div>
    <% else %>
    <div>未登録の商品です</div>
    <% end %>
    <%= f.hidden_field :item_type, value:@postage.item_type %>
  <% else %>
    <%= f.select :item_type,@postage_list,:include_blank => true %>
  <% end %>
</div>
<div class="error_message">
  <ul>
    <% @postage.errors.full_messages_for(:item_type).each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<div>
    <%= f.label :company, "運送会社" %>
    <%= f.select :company,[["ヤマト運輸","Yamato"],["佐川急便","Sagawa"],["日本郵便","Jp"]],:include_blank => true %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:company).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="hokkaido">
    <%= f.label :hokkaido, "北海道への送料" %>
    <%= f.number_field :hokkaido %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:hokkaido).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="touhoku">
    <%= f.label :touhoku, "東北への送料（日本郵便の方のみ）" %>
    <%= f.number_field :touhoku %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:touhoku).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="kitatouhoku">
    <%= f.label :kitatouhoku, "北東北への送料" %>
    <%= f.number_field :kitatouhoku %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:kitatouhoku).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="minamitohoku">
    <%= f.label :minamitouhoku, "南東北への送料" %>
    <%= f.number_field :minamitouhoku %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:minamitouhoku).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="kantou">
    <%= f.label :kantou, "関東への送料" %>
    <%= f.number_field :kantou %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:kantou).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="hokuriku">
    <%= f.label :hokuriku, "北陸への送料" %>
    <%= f.number_field :hokuriku %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:hokuriku).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="shinetsu">
    <%= f.label :shinetsu, "信越への送料" %>
    <%= f.number_field :shinetsu %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:shinetsu).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="tokyo">
    <%= f.label :tokyo, "東京への送料（日本郵便の方のみ）" %>
    <%= f.number_field :tokyo %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:tokyo).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="chubu">
    <%= f.label :chubu, "中部への送料" %>
    <%= f.number_field :chubu %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:chubu).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="kansai">
    <%= f.label :kansai, "関西への送料" %>
    <%= f.number_field :kansai %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:kansai).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="chugoku">
    <%= f.label :chugoku, "中国への送料" %>
    <%= f.number_field :chugoku %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:chugoku).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="shikoku">
    <%= f.label :shikoku, "四国への送料" %>
    <%= f.number_field :shikoku %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:shikoku).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="kyushu">
    <%= f.label :kyushu, "九州への送料" %>
    <%= f.number_field :kyushu %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:kyushu).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="kitakyusyu">
    <%= f.label :kitakyushu, "北九州への送料（佐川急便の方のみ）" %>
    <%= f.number_field :kitakyushu %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:kitakyushu).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="minamikyusyu">
    <%= f.label :minamikyushu, "南九州への送料（佐川急便の方のみ）" %>
    <%= f.number_field :minamikyushu %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:minamikyushu).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div id="okinawa">
    <%= f.label :okinawa, "沖縄への送料" %>
    <%= f.number_field :okinawa %>
</div>
<div class="error_message">
    <ul>
        <% @postage.errors.full_messages_for(:okinawa).each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<div class="submit">
    <%= button_tag disabled:true, id:"postage_submit" do %><%= yield(:button_title) %><% end %>
</div>
<% end %>

app/views/postages/_postage.html.erb
<div class="postage-title">
  <div>
    <% if postage.item_type == "MiddleBox" %>
    季節の野菜セット
    <% elsif  postage.item_type == "FewItemBox"%>
    小品目BOX
    <% else %>
    未実装商品
    <% end %>
  </div>
  <div class="empty-item">
  </div>
  <div class="data-open">
    表示
  </div>
</div>
<div class="postage-data">
  <div>
    <% if postage.company == "Yamato" %>
    <div class="title">運送会社</div><div>：ヤマト運輸</div>
    <% elsif postage.company == "Sagawa" %>
    <div class="title">運送会社</div><div>：佐川急便</div>
    <% elsif postage.company == "Jp" %>
    <div class="title">運送会社</div><div>：日本郵便</div>
    <% else %>
    <div class="title">運送会社</div><div>：エラー</div>
    <% end %>
  </div>
  <div>
    <div class="title">北海道</div><div>：<%= postage.hokkaido.to_s(:delimited) %>円</div>
  </div>
  <% if postage.company == "Jp" %>
  <div>
    <div class="title">東北</div><div>：<%= postage.touhoku.to_s(:delimited) %>円</div>
  </div>
  <% else %>
  <div>
    <div class="title">北東北</div><div>：<%= postage.kitatouhoku.to_s(:delimited) %>円</div>
  </div>
  <div>
    <div class="title">南東北</div><div>：<%= postage.minamitouhoku.to_s(:delimited) %>円</div>
  </div>
  <% end %>
  <div>
    <div class="title">関東</div><div>：<%= postage.kantou.to_s(:delimited) %>円</div>
  </div>
  <% if postage.company == "Jp" %>
  <div>
    <div class="title">東京</div><div>：<%= postage.tokyo.to_s(:delimited) %>円</div>
  </div>
  <% end %>
  <div>
    <div class="title">信越</div><div>：<%= postage.shinetsu.to_s(:delimited) %>円</div>
  </div>
  <div>
    <div class="title">北陸</div><div>：<%= postage.hokuriku.to_s(:delimited) %>円</div>
  </div>
  <div>
    <div class="title">中部</div><div>：<%= postage.chubu.to_s(:delimited) %>円</div>
  </div>
  <div>
    <div class="title">関西</div><div>：<%=postage.kansai.to_s(:delimited) %>円</div>
  </div>
  <div>
    <div class="title">中国</div><div>：<%= postage.chugoku.to_s(:delimited) %>円</div>
  </div>
  <div>
    <div class="title">四国</div><div>：<%= postage.shikoku.to_s(:delimited) %>円</div>
  </div>
  <% if postage.company == "Sagawa" %>
  <div>
    <div class="title">北九州</div><div>：<%= postage.kitakyushu.to_s(:delimited) %>円</div>
  </div>
  <div>
    <div class="title">南九州</div><div>：<%= postage.minamikyushu.to_s(:delimited) %>円</div>
  </div>
  <% else %>
  <div>
    <div class="title">九州</div><div>：<%= postage.kyushu.to_s(:delimited) %>円</div>
  </div>
  <% end %>
  <div>
    <div class="title">沖縄</div><div>：<%= postage.okinawa.to_s(:delimited) %>円</div>
  </div>
  <div class="postage-button">
    <%= link_to (button_tag "配送情報の編集", tyoe:"button"), edit_postage_path(postage) %>
  </div>
</div>

app/views/postages/edit.html.erb
<%= provide(:button_title,"設定を更新する") %>
<div class="side">
</div>
<div class="main postages-edit">
  <div class="form">
    <%= render 'form' %>
  </div>
</div>

app/views/postages/index.html.erb
<div class="side">

</div>
<div class="main postages-index">
  <div class="postages-controll">
    <%= button_to new_postage_path, method: :get  do %><%= icon('fas', 'shipping-fast') %><span>送料設定作成</span><%= icon('fas', 'chevron-right') %><% end %>
  </div>
  <div class="postages-data">
    <%= render @postages %>
  </div>
</div>

app/views/postages/new.html.erb
<%= provide(:button_title,"設定を作成する") %>
<div class="side">

</div>
<div class="main postages-new">
    <div class="oldform">
        <%= render 'form' %>
    </div>
</div>