config/routes.rb
Rails.application.routes.draw do
	mount ActionCable.server => '/cable'

	root 'static_pages#home'
	get '/home', to: 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/company', to: 'static_pages#company'
	get '/privacy', to: 'static_pages#privacy'
	get '/dashboard', to: 'static_pages#dashboard'
	get '/search_unship_order', to: 'static_pages#search_unship_order'
	get '/shipments', to:'static_pages#shipments'
	get '/introducing', to: 'static_pages#introducing'
	get '/signup', to: 'users#new'
	post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users, :except => [:new,:create]
	resources :account_activations, only: [:edit]
	resources :stocks, path: 'shipments/stocks'
	post '/shipments/stocks/complete', to: 'stocks#complete'
	resources :postages, path: 'shipments/postages'
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :items
	resources :users, shallow: true do
		resources :rooms, shallow: true do
			resources :messages
		end
	end


	namespace :admin do
		resources :postages, :stocks
		resources :users, shallow: true do
			resources :order_products, :rooms
		end
		get 'order_products/update_shipment_week/:farmer_id', to: 'order_products#update_shipment_week'
	end
	get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :room_managers, dependent: :destroy
	has_many :users, through: :room_managers
	belongs_to :order_product, optional: :true, class_name:"EcData::OrderProduct"
	has_many :messages, dependent: :destroy
	
	class << self
		def unread_total(user)
			rooms = Room.eager_load(:room_managers, :messages).where(room_managers: {user_id: user.id}).distinct
			total = 0
			for room in rooms do
				unread = room.unread_count(user)
				total += unread
			end
			return total
		end
	end
	
	def send_notification(message:, send_user:)
		received_user = User.find(received_user_id(send_user.id))
		MessageNotificationMailer.new_message(message:message, send_user:send_user, received_user:received_user).deliver_now
	end
	
	def received_user_id(send_user_id)
		uids = user_ids
		uids.delete(send_user_id)
		return uids[0]
	end
	
	def room_name
		room_name = order_product.order_list.buyer_address.lastname + order_product.order_list.buyer_address.firstname
		return room_name
	end
	
	def last_sender
		messages.order("created_at DESC").first.user.corporate_name
	end
	
	def unread_count(user)
		current_room_manger = self.room_managers.find_by(user_id: user.id)
		unread = self.messages.where("created_at >= ?", current_room_manger.accessed_at).where.not(user_id: user.id).size
		return unread
	end
	
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :admin_user?, only: [:create]
  before_action :correct_room?, only: [:show]

  def index
    @rooms = current_user.rooms
  end

  def create
    if @room = current_user.rooms.create(room_params)
      @room.room_managers.create(user_id: params[:user_id])
      redirect_to room_path(@room)
    else
      flash.now[:danger] = "メッセージスレッドの作成に失敗しました。"
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @room = current_user.room.find(params[:id])
    @messages = @room.messages
  end

  private

  def room_params
    params.require(:room).permit(:order_product_id)
  end

  def correct_user?
    access_destination_user = User.find(params[:user_id])
    return current_user ==  access_destination_user
  end

  def correct_room?
    room = Room.find(params[:id])
    return room.users.exists?(id:current_user.id)
  end

  def admin_user?
		if current_user.admin
			return true
		else
			redirect_to root_path
		end
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :admin_user?, only: [:create]
  before_action :correct_room?, only: [:show]

  def index
    @user = current_user
    @rooms = @user.rooms.preload(:order_product, {order_product: :order_list}, {:order_product => {order_list: :buyer_address}}).order("posted_at DESC")
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @order_product = @room.order_product
    @product = @order_product.product
    @buyer_address = @order_product.order_list.buyer_address
    if @buyer_address.same_sending_address
      @sending_address = @buyer_address
    else
      @sending_address = @order_product.order_list.sending_address
    end
    @messages = @room.messages.preload(:user).order("created_at ASC")
    @message = Message.new
    room_manager = @room.room_managers.find_by(user_id: @user.id)
    room_manager.update_attributes(accessed_at: Time.now)
  end

  private

  def room_params
    params.require(:room).permit(:order_product_id)
  end

  def correct_user?
    access_destination_user = User.find(params[:user_id])
    return current_user ==  access_destination_user
  end

  def correct_room?
    room = Room.find(params[:id])
    return room.users.exists?(id:current_user.id)
  end

  def admin_user?
		if current_user.admin
			return true
		else
			redirect_to root_path
		end
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<ul class="list-items--row">
	<li class="list-items--row__item"><%= room.room_name %></li>
	<li class="list-items--row__item"><%= room.last_sender %></li>
	<li class="list-items--row__item"><%= room.posted_at.strftime("%Y年%m月%d日 %H:%M") %></li>
	<li class="list-items--row__item"><%= room.unread_count(@user) %></li>
	<li class="list-items--row__item"><%= link_to "詳細", room_path(room) %></li>
</ul>

app/views/rooms/index.html.erb
<div class="side">
	<%= render 'layouts/dashboard_sidebar' %>
</div>
<div class="main room_index">
	<h1>メッセージボード一覧</h1>
	<ul class="list-items--column sp-list-items--column">
		<ul class="list-items--row">
			<li class="list-items--row__item">購入者</li>
			<li class="list-items--row__item">最終投稿者</li>
			<li class="list-items--row__item">最終投稿時間</li>
			<li class="list-items--row__item">未読数</li>
			<li class="list-items--row__item"></li>
		</ul>
		<%= render @rooms %>
	</ul>
</div>

app/views/rooms/show.html.erb
<div class="side">
	<%= render 'layouts/dashboard_sidebar' %>
</div>
<div class="main room_show">
	<ul class="list-items--column">
		<h2>注文情報</h2>
		<ul class="list-items--row">
			<li class="list-items--row__item">購入日時</li>
			<% if @buyer_address.desired_delivery %>
			<li class="list-items--row__item">配送指定日時</li>
			<% end %>
			<li class="list-items--row__item product-name">注文内容</li>
			<li class="list-items--row__item quantity">数量</li>
			<li class="list-items--row__item">購入者氏名</li>
			<li class="list-items--row__item">送付先氏名</li>
			<li class="list-items--row__item address">送付先住所</li>
		</ul>
		<ul class="list-items--row">
			<li class="list-items--row__item"><%= @order_product.bought_time.strftime("%m月%d日 %H:%M") %></li>
			<% if @buyer_address.desired_delivery %>
			<li class="list-items--row__item"><%= @buyer_address.shipment_date %>　<%= @buyer_address.shipment_time %></li>
			<% end %>
			<li class="list-items--row__item product-name"><%= @product.name %></li>
			<li class="list-items--row__item quantity"><%= @order_product.quantity %></li>
			<li class="list-items--row__item"><%= @buyer_address.lastname %><%= @buyer_address.firstname %></li>
			<li class="list-items--row__item"><%= @sending_address.lastname %><%= @sending_address.firstname %></li>
			<li class="list-items--row__item address"><%= @sending_address.pref %><%= @sending_address.city %><%= @sending_address.street %><%= @sending_address.building %></li>
		</ul>
	</ul>
	<div class="message-container">
		<h2>メッセージボード</h2>
		<div class="button-container">
			<button onclick="MessageScrollUp()"><%= icon('fas','arrow-up') %>最上部へ</button>
			<button onclick="MessageScrollDown()"><%= icon('fas','arrow-down') %>最下部へ</button>
		</div>
		<div id="messages">
			<%= render @messages %>
		</div>
	</div>
	<%= form_for( @message , remote: true, url: room_messages_path(@room) ,html: {class: "chat-form"}) do |f| %>
		<%= f.text_area :content, class: "chat-form__text-area" %>
		<%= f.hidden_field :room_id, value: params[:id] %>
		<button type="submit" class="chat-form__submit">送信</button>
	<% end %>
</div>
<script>
function MessageScrollUp() {
	$("#messages").animate({scrollTop: 0}, 'fast');
}
function MessageScrollDown() {
	$("#messages").animate({scrollTop: $("#messages")[0].scrollHeight}, 'fast');
}
</script>