config/routes.rb
Rails.application.routes.draw do
	mount ActionCable.server => '/cable'

	root 'static_pages#home'
	get '/home', to: 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/company', to: 'static_pages#company'
	get '/privacy', to: 'static_pages#privacy'
	get '/dashboard', to: 'static_pages#dashboard'
	get '/search_unship_order', to: 'static_pages#search_unship_order'
	get '/shipments', to:'static_pages#shipments'
	get '/introducing', to: 'static_pages#introducing'
	get '/signup', to: 'users#new'
	post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users, :except => [:new,:create]
	resources :account_activations, only: [:edit]
	resources :stocks, path: 'shipments/stocks'
	post '/shipments/stocks/complete', to: 'stocks#complete'
	resources :postages, path: 'shipments/postages'
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :items
	resources :users, shallow: true do
		resources :rooms, shallow: true do
			resources :messages
		end
	end


	namespace :admin do
		resources :postages, :stocks
		resources :users, shallow: true do
			resources :order_products, :rooms
		end
		get 'order_products/update_shipment_week/:farmer_id', to: 'order_products#update_shipment_week'
	end
	get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/ec_data/user.rb
module EcData
  class User < EcData::Base
    self.primary_key = "id"
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_create :create_activation_digest
  before_validation { self.email = email.downcase }
  before_validation { self.phone = phone.gsub(/-/, '')}
  before_validation { self.zipcode = zipcode.gsub(/-/, '')}
  validates :corporate_name, presence: true
  validates :lastname, presence: true
  validates :firstname, presence: true
  VALID_KANA_REGEX = /\A[ァ-ンー－]+\z/
  validates :lastname_phonetic, presence: true, format: { with: VALID_KANA_REGEX }
  validates :firstname_phonetic, presence: true, format: { with: VALID_KANA_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  VALID_NUMBER_REGEX = /\A\d+\z/
  validates :phone, presence: true, length: { maximum: 11 }, format: { with: VALID_NUMBER_REGEX}
  validates :zipcode, presence: true, length: { is: 7 }, format: { with: VALID_NUMBER_REGEX}
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  validates :pref, presence:true
  validates :city, presence:true
  validates :street, presence: true
  
  has_many :stocks, dependent: :destroy
  has_many :postages, dependent: :destroy
  has_many :product_items, dependent: :destroy
  has_many :products, through: :product_items, class_name:"EcData::Product", source: :product
  has_many :room_managers
  has_many :rooms, through: :room_managers
  has_many :messages

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true , activated_at:Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_id).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_id = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attributes(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now )
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 1.hours.ago
  end

  private

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
	def index
		@users = User.preload(:stocks,{stocks: :order_products}).paginate(page: params[:page], per_page: 10)
	end

	def show
		@user = User.find(params[:id])
		@order_products = ::EcData::OrderProduct.where(stock_id: @user.stock_ids).where(trailing_id: nil).order("bought_time DESC").paginate(page: params[:page], per_page: 10)
	end
	
	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to "index", flash: {success: "ユーザーの削除が完了しました"}
		else
			redirect_to "index", flash: {danger: "ユーザーの削除に失敗しました"}
		end
	end

	private

	def user_params
		params.require(:user).permit(:corporate_name, :lastname,:firstname, :lastname_phonetic, :firstname_phonetic, :email, :phone,:zipcode, :pref,:area,:city,:street,:building, :password, :password_confirmation)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "仮登録メールを送信しました。メールからアカウントの有効化を行ってください。"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      unless @user.stocks.blank?
        stocks = @user.stocks
        stocks.each do | stock |
          stock.area = @user.area
          stock.pref = @user.pref
          stock.save
        end
      end
      flash[:success] = "ユーザー情報の更新が完了しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to users_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:corporate_name, :lastname,:firstname, :lastname_phonetic, :firstname_phonetic, :email, :phone,:zipcode, :pref,:area,:city,:street,:building, :password, :password_confirmation)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user.html.erb
<% unship_count = user.stocks.map { |stock| stock.order_products.eager_load(:order_list, { order_list: :buyer_address }, { order_list: :payment }).where(payments: {paid: true}).where.not(addresses: {desired_delivery: true}).where(trailing_id: nil).pluck(:quantity).sum}.sum %>
<% desired_delivery_count = user.stocks.map { |stock| stock.order_products.eager_load(:order_list, { order_list: :buyer_address }, { order_list: :payment }).where(payments: {paid: true}).where(addresses: {desired_delivery: true}).where(trailing_id: nil).pluck(:quantity).sum}.sum %>
<ul class="list-items--row sp-list-items--row">
  <li class="list-items--row__item sp-list-items--row__item">
    <%= user.corporate_name %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item">
    <% if unship_count == 0 %>
      <%= unship_count %>
    <% else %>
      <%= link_to "#{unship_count}", admin_user_order_products_path(user_id: user.id, params:{ unship_order: true}) %>
    <% end %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item">
    <% if desired_delivery_count == 0 %>
      <%= desired_delivery_count %>
    <% else %>
      <%= link_to "#{desired_delivery_count}", admin_user_order_products_path(user_id: user.id, params:{ desired_delivery: true}) %>
    <% end %>
  </li>
  <li class="list-items--row__item sp-list-items--row__item">
    <%= link_to "詳細", admin_user_path(user) %>
  </li>
</ul>

app/views/admin/users/index.html.erb
<div class="side">
	<%= render 'layouts/dashboard_sidebar' %>
</div>
<div class="main admin-user_index">
  <ul class="list-items--column sp-list-items--column">
    <ul class="list-items--row sp-list-items--row">
      <li class="list-items--row__item sp-list-items--row__item">法人名</li>
      <li class="list-items--row__item sp-list-items--row__item">未発送の箱数</li>
      <li class="list-items--row__item sp-list-items--row__item">日時指定注文の未発送箱数</li>
      <li class="list-items--row__item sp-list-items--row__item"></li>
    </ul>
    <%= render @users %>
  </ul>
</div>

app/views/admin/users/show.html.erb
<div class="side">
  <%= render 'layouts/dashboard_sidebar' %>
</div>
<div class="main admin-user_show">
  <h1><%= @user.corporate_name %></h1>
  <ul class="list-items--column sp-list-items--column">
    <ul class="list-items--row sp-list-items--row">
      <li class="list-items--row__item sp-list-items--row__item">名前</li>
      <li class="list-items--row__item sp-list-items--row__item">フリガナ</li>
      <li class="list-items--row__item sp-list-items--row__item">住所</li>
      <li class="list-items--row__item sp-list-items--row__item">電話番号</li>
      <li class="list-items--row__item sp-list-items--row__item">メールアドレス</li>
    </ul>
    <ul class="list-items--row sp-list-items--row">
      <li class="list-items--row__item sp-list-items--row__item"><%= @user.lastname %><%= @user.firstname %></li>
      <li class="list-items--row__item sp-list-items--row__item"><%= @user.lastname_phonetic %><%= @user.firstname_phonetic %></li>
      <li class="list-items--row__item sp-list-items--row__item"><%= @user.pref %><%= @user.city %><%= @user.street %><%= @user.building %></li>
      <li class="list-items--row__item sp-list-items--row__item"><%= @user.phone %></li>
      <li class="list-items--row__item sp-list-items--row__item"><%= @user.email %></li>
    </ul>
  </ul>
  <ul class="list-items--column sp-list-items--column">
    <ul class="list-items--row sp-list-items--row">
      <li class="list-items--row__item sp-list-items--row__item label">生産品目一覧</li>
      <li class="list-items--row__item sp-list-items--row__item data">生産品目の一覧を設定できるようにする予定</li>
    </ul>	
    <ul class="list-items--row sp-list-items--row">
      <li class="list-items--row__item sp-list-items--row__item label">今月の生産品目</li>
      <li class="list-items--row__item sp-list-items--row__item data">今月の生産品目の一覧を設定できるようにする予定</li>
    </ul>
  </ul>
  <ul class="list-items--column sp-list-items--column">
    <ul class="list-items--row sp-list-items--row">
      <li class="list-items--row__item sp-list-items--row__item">購入日</li>
      <li class="list-items--row__item sp-list-items--row__item">商品名</li>
      <li class="list-items--row__item sp-list-items--row__item quantity">数量</li>
      <li class="list-items--row__item sp-list-items--row__item">発送先氏名</li>
      <li class="list-items--row__item sp-list-items--row__item sending-address">発送先住所</li>
      <li class="list-items--row__item sp-list-items--row__item quantity">入金</li>
      <li class="list-items--row__item sp-list-items--row__item">配送指定</li>
      <li class="list-items--row__item sp-list-items--row__item">発送状況</li>
      <li class="list-items--row__item sp-list-items--row__item button"></li>
      <li class="list-items--row__item sp-list-items--row__item button"></li>
    </ul>
    <%= render :partial => "/admin/order_products/op", :collection => @order_products %>
    <%= link_to "注文一覧へ移動", admin_user_order_products_path(@user) %>
  </ul>
</div>